### ISSUE TITLE
Docs: Create machine learning resources folder

### ISSUE THREAD

**Issue by motuncoded** [SCA-OAU/LearnLink#15]
I would love to contribute by creating a machine learning resources folder. 

Kindly assign this to me

**Comment by Charity10** [comment]
we would appreciate that😊
Are you into machine learning? @motuncoded

**Comment by motuncoded** [comment]
Currently no but i have a brother doing that...

**Comment by ArafatAbdussalam** [comment]
Hi @motuncoded You can go ahead with it.

**Comment by motuncoded** [comment]
Thanks glad to do this

**Comment by motuncoded** [comment]
Kindly add the hacktoberfeat label to this issue
