### ISSUE TITLE
Docs: Create a section Technical writing 

### ISSUE THREAD

**Issue by motuncoded** [SCA-OAU/LearnLink#23]
- Create different sections of technical writing 
- Add the list of resources to technical writing

**Comment by ArafatAbdussalam** [comment]
Hi @motuncoded Can you explain more of what you intend to write on the different sections of technical writing?

**Comment by motuncoded** [comment]
I will be add a list of resources for beginners, intermediate and advanced sections. Here are some


Introduction to Technical Writing (Google) 
Technical Writing for Beginners (freeCodeCamp) 
How to Write Documentation (Write the Docs)
API documentation etc

**Comment by ArafatAbdussalam** [comment]
Alright. You can go ahead with it.

I commend the fact that you’re creating issues for your contribution. That’s a good principle. Also, your style of writing the title is commendable.

**Comment by motuncoded** [comment]
Kindly add the hacktoberfest label to this issue
